[2025-08-26T10:55:59.767+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mamda_monthly_etl_pipeline.run_db_to_file_etl manual__2025-08-26T10:55:57.253624+00:00 [queued]>
[2025-08-26T10:55:59.775+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mamda_monthly_etl_pipeline.run_db_to_file_etl manual__2025-08-26T10:55:57.253624+00:00 [queued]>
[2025-08-26T10:55:59.776+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-26T10:55:59.792+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): run_db_to_file_etl> on 2025-08-26 10:55:57.253624+00:00
[2025-08-26T10:55:59.798+0000] {standard_task_runner.py:60} INFO - Started process 144 to run task
[2025-08-26T10:55:59.802+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mamda_monthly_etl_pipeline', 'run_db_to_file_etl', 'manual__2025-08-26T10:55:57.253624+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/mamda_monthly_etl.py', '--cfg-path', '/tmp/tmp846q0hvj']
[2025-08-26T10:55:59.804+0000] {standard_task_runner.py:88} INFO - Job 244: Subtask run_db_to_file_etl
[2025-08-26T10:55:59.851+0000] {task_command.py:423} INFO - Running <TaskInstance: mamda_monthly_etl_pipeline.run_db_to_file_etl manual__2025-08-26T10:55:57.253624+00:00 [running]> on host 54c08829cb2d
[2025-08-26T10:55:59.937+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mamda_etl' AIRFLOW_CTX_DAG_ID='mamda_monthly_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_db_to_file_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-08-26T10:55:57.253624+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-26T10:55:57.253624+00:00'
[2025-08-26T10:55:59.938+0000] {mamda_monthly_etl.py:75} INFO - === START: DB -> FILE ETL ===
[2025-08-26T10:56:01.825+0000] {mamda_monthly_etl.py:89} INFO - DB->FILE STDOUT:
AVERTISSEMENT: Dossier externe non accessible ou non défini dans .env
Utilisation du dossier local à la place.
Utilisation du dossier local: /opt/***/data/fee_payouts
AVERTISSEMENT: Un fichier avec la référence '3AV1024' existe déjà.
Fichier existant: 3AV1024_20250826_105246.asc
Génération annulée pour éviter les doublons.
AVERTISSEMENT: Dossier externe non accessible ou non défini dans .env
Utilisation du dossier local à la place.
Utilisation du dossier local: /opt/***/data/fee_payouts
AVERTISSEMENT: Un fichier avec la référence '3EX1024' existe déjà.
Fichier existant: 3EX1024_20250826_105247.asc
Génération annulée pour éviter les doublons.
AVERTISSEMENT: Dossier externe non accessible ou non défini dans .env
Utilisation du dossier local à la place.
Utilisation du dossier local: /opt/***/data/fee_payouts
AVERTISSEMENT: Un fichier avec la référence '3ME1024' existe déjà.
Fichier existant: 3ME1024_20250826_105248.asc
Génération annulée pour éviter les doublons.
AVERTISSEMENT: Dossier externe non accessible ou non défini dans .env
Utilisation du dossier local à la place.
Utilisation du dossier local: /opt/***/data/fee_payouts
AVERTISSEMENT: Un fichier avec la référence '3CO1024' existe déjà.
Fichier existant: 3CO1024_20250826_105248.asc
Génération annulée pour éviter les doublons.

[2025-08-26T10:56:01.826+0000] {mamda_monthly_etl.py:91} WARNING - DB->FILE STDERR:
INFO:__main__:---- DÉMARRAGE DU PIPELINE DB -> FILE ----
INFO:__main__:--- Traitement pour base: sinauto_mcma_, type_aux: A ---
INFO:__main__:Données extraites avec succès pour sinauto_mcma_
INFO:__main__:sinauto_mcma_ : mapping réussi
INFO:__main__:sinauto_mcma_ : transformation réussie
INFO:__main__:sinauto_mcma_ : fichier SIMT généré
INFO:__main__:--- Traitement pour base: sinauto_mcma_, type_aux: E ---
INFO:__main__:Données extraites avec succès pour sinauto_mcma_
INFO:__main__:sinauto_mcma_ : mapping réussi
INFO:__main__:sinauto_mcma_ : transformation réussie
INFO:__main__:sinauto_mcma_ : fichier SIMT généré
INFO:__main__:--- Traitement pour base: sinauto_mcma_, type_aux: M ---
INFO:__main__:Données extraites avec succès pour sinauto_mcma_
INFO:__main__:sinauto_mcma_ : mapping réussi
INFO:__main__:sinauto_mcma_ : transformation réussie
INFO:__main__:sinauto_mcma_ : fichier SIMT généré
INFO:__main__:--- Traitement pour base: sinauto_mcma_, type_aux: C ---
INFO:__main__:Données extraites avec succès pour sinauto_mcma_
INFO:__main__:sinauto_mcma_ : mapping réussi
INFO:__main__:sinauto_mcma_ : transformation réussie
INFO:__main__:sinauto_mcma_ : fichier SIMT généré
INFO:__main__:---- FIN DU PIPELINE DB -> FILE ----

[2025-08-26T10:56:01.826+0000] {mamda_monthly_etl.py:99} INFO - === DONE: DB -> FILE ETL ===
[2025-08-26T10:56:01.827+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-08-26T10:56:01.836+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=mamda_monthly_etl_pipeline, task_id=run_db_to_file_etl, execution_date=20250826T105557, start_date=20250826T105559, end_date=20250826T105601
[2025-08-26T10:56:01.864+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-26T10:56:01.886+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
